networks:
  proxy:
    name: proxy
    driver: bridge

services:
  traefik:
    image: traefik:v3.6
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=info.francescobianco@gmail.com
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
    ports:
      - 80:80
      - 443:443
    environment:
      - DOCKER_API_VERSION=1.46
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
    networks:
      - proxy
    restart: always
